title: Rabia's Portfolio
description: Personal portfolio website for Rabia2698
theme: jekyll-theme-cayman

show_downloads: true
google_analytics: UA-XXXXXXXXX-X  # Replace with your actual Google Analytics tracking ID
